baseURL: "/"
title: "keptn"
enableRobotsTXT: true
enableEmoji: true

# Language configuration
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true

# Provide .LastMod values
enableGitInfo: true

contentDir: "content/en"

taxonomies:
  tag: "tags"
  category: "categories"

module:
  proxy: direct
  hugoVersion:
    extended: true
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false


# Markup settings
# Ref: https://gohugo.io/getting-started/configuration-markup#goldmark
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style: friendly
  parser:
    autoHeadingID: true
    autoHeadingIDType: github

languages:
  en:
    languageName: English
    languageCode: en
    time_format_default: 2006-01-02
    time_format_blog: 2006-01-02

permalinks:
  blog = "/:section/:year/:month/:day/:slug/"

imaging:
  resampleFilter: "CatmullRom"
  quality: 75
  anchor: "smart"

outputs:
  home: [HTML]
  page: [HTML]

params:
  description: Cloud-native application life-cycle orchestration
  copyright: Keptn Community
  github_repo: https://github.com/keptn/lifecycle-toolkit
  github_branch: main
  github_project_repo: https://github.com/keptn/lifecycle-toolkit
  slack: https://cloud-native.slack.com/messages/keptn
  # Enable Algolia DocSearch
  algolia_docsearch: false
  offlineSearch: true
  version_menu: "Releases"
  version: "0.4.1"
  url_latest_version: https://lifecycle.keptn.sh
  taxonomy:
    pygmentsCodeFences: true
    pygmentsUseClasses: true
    pygmentsUseClassic: false

    taxonomyCloud:
      - "tags"
      - "categories"

    taxonomyCloudTitle:
      - "tags"
      - "categories"

    taxonomyPageHeader:
      - "tags"
      - "categories"

  ui:
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_menu_truncate: 1000
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: false
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    navbar_logo: true
    # Set to true to disable the About link in the site footer
    footer_about_disable: false
    header_search_disable: true
  markmap:
    enable: true
  links:
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    user:
      - name: Twitter
        url: "https://twitter.com/KeptnProject"
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
      - name: LinkedIn
        url: https://www.linkedin.com/company/keptnproject
        icon: fab fa-linkedin
    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    developer:
      - name: GitHub
        url: "https://github.com/keptn/lifecycle-toolkit"
        icon: fab fa-github
        desc: Development takes place here!
      - name: Slack
        url: https://cloud-native.slack.com/messages/keptn
        icon: fab fa-slack
        desc: Chat with other project developers
      - name: Keptn YouTube channel
        url: https://youtube.com/@keptn
        icon: fab fa-youtube
        desc: Watch videos about Keptn